### ISSUE TITLE
[KOGITO-9785] Option to configure timeout error handler

### ISSUE THREAD

**Issue by dmartinol** [apache/incubator-kie-kogito-runtimes#3254]
### Description

Allow the SWF developer to define an `onError` configuration to detect an expired timeout in the current state, and trigger the desired `transition`, as in :
```yaml
errors:
  - name: timeoutError
    code: '_TIMEOUT_CODE_'
...
    timeouts:
      eventTimeout: '_TIMEOUT_'
    onErrors:
      - errorRef: timeoutError
        transition: '_TRANSITION_IN_CASE_OF_TIMEOUT_'
```
