### ISSUE TITLE
Infer data type when publishing cloud event 

### ISSUE THREAD

**Issue by gabriel-farache** [apache/incubator-kie-kogito-runtimes#3383]
### Description

Currently, the following state:
```
    transition:
      nextState: WaitForSaveTransformationCompletionEvent
      produceEvents:
        - eventRef: saveTransformationEvent
          data: "{gitRepo:.repositoryURL|sub(\"http(s)?://\";\"ssh://\"), branch: .targetBranch, token: .token, workspaceId: .workspaceId, projectId: .projectId, transformId: .transformId, workflowCallerId: $WORKFLOW.instanceId}"

```
will produce the following event:
```
ProcessInstanceDataEvent {specVersion=1.0, id='293b7596-1253-4c98-ac12-4e9825f01bce', source=/process/m2k, type='save-transformation', time=2024-01-30T13:24:14.595998574Z, subject='null', dataContentType='null', dataSchema=null, data={"gitRepo":"ssh://bitbucket.org/gfarache31/m2k-test","branch":"aaaaaaasssss","token":null,"workspaceId":"b93980cb-3943-4223-9441-8694c098eeb9","projectId":"9b305fe3-d441-48ce-b01b-d314e86e14ec","transformId":"723dce89-c25c-4c7b-9ef3-842de92e6fe6","workflowCallerId":"7ddb5193-bedc-4942-a857-596b31f377ed"}, kogitoProcessInstanceId='7ddb5193-bedc-4942-a857-596b31f377ed', kogitoRootProcessInstanceId='null', kogitoProcessId='m2k', kogitoRootProcessId='null', kogitoAddons='null', kogitoIdentity='null', extensionAttributes={kogitoproctype=SW, kogitoprocinstanceid=7ddb5193-bedc-4942-a857-596b31f377ed, kogitoprocist=Active, kogitoprocversion=1.0, kogitoprocid=m2k}}

```

The `dataContentType` being null is causing error on the receiver ends as it does not know how to properly parse the `data`

The  `dataContentType` shall be inferred when publishing event
