### ISSUE TITLE
Serverless workflow switch issue: when two branches pointing to the same transition, it treats the conditions as "and"

### ISSUE THREAD

**Issue by shootsoft** [apache/incubator-kie-kogito-runtimes#3456]
### Describe the bug

I'm using serverless workflow, in a "switch" state, I defined two branches pointing to the same transitions. I'm expecting the "switch" will route the workflow to the first condition matched. However, the actual match is "switch" seems treat two branches as "and", which unless both conditions get matched, switch won't jump to the expected branch.

### Expected behavior

Output

```
{workflowdata={"condition1":true,"condition2":false,"output":"branch1"}}
```

### Actual behavior

Output

```
{workflowdata={"condition1":true,"condition2":false,"output":"default"}}
```

### How to Reproduce?

Workflow Yaml file

```yaml
id: switch
version: 1.0.0
specVersion: "0.8"
name: Switch test
start: switch test
states:
  - name: switch test
    type: switch
    dataConditions:
      - name: Branch1-Name
        condition: .condition1
        transition: branch1
      - name: Branch2-Name
        condition: .condition2
        transition: branch1

    defaultCondition:
      transition: default

  - name: branch1
    type: inject
    data:
      output: branch1
    end: true


  - name: default
    type: inject
    data:
      output: default
    end: true
 
```

Test java code

```java
@Test
public void testKogitoSwitch() throws Exception {
    final Map<String, Object> input = ImmutableMap.of(
            "condition1", true,
            "condition2", false);

    try (StaticWorkflowApplication application = StaticWorkflowApplication.create()) {
        var process = application.process(getWorkflowFromResource("workflow/switch.sw.yaml"));
        var processInstance = process.createInstance(new JsonNodeModel(input));
        processInstance.start();
        final JsonNodeModel model = processInstance.variables();
        System.out.println(model.toMap());
    }
}
```

If change the input as

```java
   final Map<String, Object> input = ImmutableMap.of(
            "condition1", true,
            "condition2", true);
```

Output would be
```
{workflowdata={"condition1":true,"condition2":true,"output":"branch1"}}
```

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

2.44.0.Alpha, 1.44.0.Final

**Comment by ricardozanini** [comment]
Hi! I couldn't try your workflow locally, but can you try changing the condition to:

```
${ .condition1 == true }
```

and

```
${ .condition2 == true }
```

Just to rule out a problem in the jq expression evaluation. Yes, the switch should match the first true condition.

**Comment by shootsoft** [comment]
@ricardozanini 

I've tried update the yaml to 

```yaml
      - name: Branch1-Name
        condition: ${ .condition1 == true }
        transition: branch1
      - name: Branch2-Name
        condition: ${ .condition2 == true }
        transition: branch1
```

With input

```java
final Map<String, Object> input = ImmutableMap.of(
                "condition1", true,
                "condition2", false);
```

The output is still

```javascript
{workflowdata={"condition1":true,"condition2":false,"output":"default"}}
```

The problem is if I provide both conditions input as true, it can go to "branch1". Use "${}" and "==true" or not.

**Comment by ricardozanini** [comment]
Yeah, this seems like a bug. I'm assigning it to a colleague who will take a look as soon as possible.

**Comment by fjtirado** [comment]
@shootsoft Well, this is not real life  use case. Two different conditions pointing to the same branch is not something that will ever happen, in my opinion, beside this synthetic use case.
You can achieve the desired behaviour by modifying the  yaml to 
```
id: switch
version: 1.0.0
specVersion: "0.8"
name: Switch test
start: switch test
states:
  - name: switch test
    type: switch
    dataConditions:
      - name: Branch1-Name
        condition: .condition1 or .condition2
        transition: branch1
    defaultCondition:
      transition: default

  - name: branch1
    type: inject
    data:
      output: branch1
    end: true


  - name: default
    type: inject
    data:
      output: default
    end: true
 
```
