### ISSUE TITLE
data field is ignored in ProduceEvents in End transitions

### ISSUE THREAD

**Issue by fjtirado** [apache/incubator-kie-kogito-runtimes#3902]
### Describe the bug

When using ProduceEvents on end, the data fields is ignored

```
- name: releaseLock
    type: operation
    actions:
      - functionRef:
          refName: sysLog
          arguments:
            message: ${ "Lock " +  .name +  " released" }
    end:
      produceEvents:
        - eventRef: released-event
          data: '{param1:"1", param2:"2"}'     

```

It works when used on regular transitions. 

```
  - name: releaseLock
    type: operation
    actions:
      - functionRef:
          refName: sysLog
          arguments:
            message: ${ "Lock " +  .name +  " released" }
    transition:
      nextState: complete
      produceEvents:
        - eventRef: released-event
          data: '{test: "testYOOOOOOOOOOOOOOOO"}'
  - name: complete
    type: operation
    actions:
      - functionRef:
          refName: sysLog
          arguments:
            message: ${ "END" }
    end: true
```

The explanations is a bug in the search algorithm of getAction for EndNodeVisitor
